export const artistsArr = [
  {
    name: "Jeremy Sicile-Kira",
    bio: [
      "My name is Jeremy Sicile-Kira.",
      "I am a visionary artist -  I paint my dreams. I have become an award-winning professional artist,  and an inspirational presenter  despite being labelled severely autistic.  As a child,  my parents were given no hope for my future, yet my mom took me out of darkness when she  taught me to communicate by pointing to letters as I could not speak due to motor challenges.  As a student, an MTV crew followed me for their documentary series, True Life for their award-winning episode:  “I have Autism.” In 2011, I began to tell others about my dreams: dreams that I was painting the emotions of people into colorful abstract portraits. One night I dreamt that I  painted ten of my paintings and had an art show. I was encouraged to make this dream come true, and began to paint in real life. In 2016 my first curated solo art show was covered by national and local media, resulting in a sold-out show and many private commissions. I have participated in museum shows in California,  and art shows around the country and provided inspirational presentations using voice output technology to colleges and schools. Art collectors in the US and Europe  have commissioned or bought paintings to add to their collections.  A short documentary  “The Beautiful Colors of Jeremy Sicile-Kira” by director Aaron Lemle was released in mid- 2021 and shown at movie festivals to critical acclaim. ",
      "I have synesthesia, which  means that my senses are mixed. I see letters, numbers, and words in color. Music, voices and emotions elicit color as well. I do not see the emotions on people’s dear faces; I only see the colors of their emotions.  I experience the world through a storm of colors. When I leave my apartment, all I see is color everywhere which represents the emotions and the energy of the living things in that space.  However, I have learned  how to use this overwhelming synesthesia as a gift to help others. My mission as an artist  is to provide Hope to others because Hope is a necessary attribute to overcome life's challenges. I meet with clients, listen to them speak and “read” their colors. Then I paint their bright and abstract  portrait, and provide a description of the colors that reveal their inner abilities and spiritual essence. When I am painting, I can focus on just the paint, and the music which I listen to in order to keep a rhythm dearly necessary for my motor control.  In the last few years I have begun to paint the colors of positive human emotions such as Gratitude, Joy, Happiness so that people can have a daily reminder of the positive attributes we all can aspire to.  I have partnered with companies such as Perfect Farewells to create memorial paintings of loved ones who have passed. In my digital art and paintings, a positive emotional connection is made with all who see the image. ",
      "I love the opportunity for my art to be enjoyed by collectors I might not meet at art shows or galleries. I greatly believe art should be enjoyed by all, but I am also mindful that the art must have some elements of exclusivity.  I am excited about this unique way of creating online communities  around a shared love of art.",
    ],
    image: "Jermey.png",
    visual1: "jeremy1.PNG",
    visual2: "jeremy2.PNG",
    visual3: "jeremy3.PNG",
    address: "0xa11edf642d6f080f2e07bacfbb5cb951d9701632",
  },
  {
    name: "Ali Shahrouzi",
    bio: [
      "My name is Ali Shahrouzi.",
      "Ali Shahrouzi is a fine-art photographer who has dedicated most of his life to photography. He has always been interested in the arts and began experimenting with painting and photography at around 15 years old. Eventually, the camera took the place of the paint brush because it have him more visual control of his expression. His interest in photography began in HIgh School, as he spent many hours in the darkroom printing. One thing led to another, and soon Ali was offered a scholarship to attend Brooks Institute of Photography in Santa Barbara, California. Since then, his work has been published in many national and international publications, including Popular Photography, Petersen's Photographic, Rangefinder, Santa Barbara Destination Guide, and many more.",
      "Ali has cerebral palsy, and has no usage of his hands or legs. He is completely wheelchair bound. When he’s behind the camera, he uses an assistant's hands to compose his images while looking through the view finder. The assistant stands by and listens as he directs, “higher, lower, left, right”, waiting for the perfect composition to come into frame. All camera setting decisions are directed and controlled by Ali.",
      "When in the darkroom, all fine art black and white prints are done by hand the traditional way; optically and chemically processed under his supervision every step of the process. All of his black and white fine art silver gelatin prints are done on ilford senimat fiber based paper, and toned selenium, so they last for generations to enjoy.",
    ],
    image: "alidaniels.jpg",
    visual1: "ali1.jpg",
    visual2: "ali2.jpg",
    visual3: "ali3.jpg",
    address: "0x3f81ec7c68086f73fb658b900f58a8fc674c6b10",
  },
  {
    name: "Marrie Bottleson",
    bio: [
      "My name is Marrie Bottelson.",
      "I'm an artist. Because my art makes me happy and I want others to look at my art work and they  feel happy. I also mark art to stand up for myself, to feel proud and to show the world that it takes a lot of strength for me to make art.",
      "I like working with acrylic paints on canvas. I like how paint feels when I’m moving it around with a brush and I like to see what I can do with it. I used to paint fish and trees, but now I’m into cats and dogs.",
      "I hope you like my artwork",
    ],
    image: "marrie.png",
    visual1: "marrie1.jpg",
    visual2: "marrie2.jpg",
    visual3: "marrie3.JPG",
    address: "0xa783a4e326c5a7ee1f3861727b3d449142d4d33a",
  },
  {
    name: "Matt Sully",
    bio: [
      "My name is Matthew 'Sully' Sullivan.",
      "I was born with Cerebral Palsy, but that has not stopped me from going after my creative dreams. Through the encouragement of my high school teacher, Mr. Sporn, and my caretaker, Liz, I have found ways to express myself through art.",
      "Painting and sketching allow me to show others how my mind works. Although I do things a little differently than others and some have seen that as a disability, I find that what makes me different is a strength. My art is inspired by my story, and now I want to share my story with you.",
      "I hope you enjoy.",
    ],
    image: "matt.png",
    visual1: "matt1.jpg",
    visual2: "matt2.jpg",
    visual3: "matt3.jpg",
    address: "0xc277c16e965d86cacf291807c14b1f338ddcdaca",
  },
  {
    name: "John Bramblitt",
    bio: [
      "My name is John Bramblitt",
      "I am a painter, author, and speaker who is visually impaired. After losing my sight in 2001, I decided to pick up a paintbrush. I never expected anyone to see any of my paintings; I just knew I needed to reconnect with the visual world I had lost. Since then my work has been featured in major news outlets and traveled the world. I have worked with celebrities such as Tony Hawk, Jeff Bridges, and Lyle Lovett, among others. In 2017 I partnered with Delta to paint a Boeing 737 promoting the Rock-in-Rio concert. I have received three presidential service awards for my innovative multi-sensory art workshops and have been named a Cultural Ambassador to the US. Not only am I ranked as the #1 blind painter in the world, but I am also now the only blind muralist having completed projects in New York, Dallas, and Fort Worth. I enjoy sharing my story with audiences around the world, energizing organizations, and motivating people to exceed their limits. My unique journey from the dark has enabled me to connect with a visual world and act as a beacon for others experiencing struggles.",
      "Being an artist gave me a way to explore this new perceptual world that I found myself in, and more importantly a way to reach out and connect with those around me. Color has more meaning for me since having lost my vision, and in truth, the world is a far more colorful place now than when I was sighted. I am no longer limited to the arbitrary colors of objects that the eye sees. Color is so much more than this – it is emotion and feeling; for me, it is the expression of the inner unseen nature of the object or person being observed. The way that I ‘see’ with my hands is real and concrete – I visualize, in my mind, through touch. Many of my pieces include figurative or written elements; I think of these as the bones of the painting; they are the framework on which the color of the painting hangs. I enjoy using combinations of both figurative and abstract elements in my work; to me, it most accurately represents the blending of the physical, intellectual, and emotional aspects that all come together to form our perception. The world around us is filled with poetry; with physical metaphors that add to our understanding and give breadth and depth to our lives. They add color and vitality to what otherwise could be a very bleak and unremarkable landscape. With the right kind of eyes, you can see beneath the skin of things; you can lift the veil, and see to the true color of what lies around us.",
      "NFT's are so exciting because they introduce a whole new relationship between artist, art, and collector. It has created opportunities for artists of all mediums and levels in their careers; we are no longer restricted to the walls of a gallery. I am also so excited about how will introduce new ideas of exclusivity. There are so many opportunities to connect with people that enjoy your art while offering them something completely unique.",
    ],
    image: "John_photo.jpg",
    visual1: "john1.jpg",
    visual2: "john2.jpg",
    visual3: "john3.jpg",
    address: "0xbfa9be16dd21563b6a950ea91cb9185e600a12f8",
  },
];
