export const artistsArr = [
  {
    name: "Jeremy Sicile-Kira",
    bio: [
      "My name is Jeremy Sicile-Kira. I am a visionary artist. I paint my dreams.",
      "In 2012 I communicated to others that I was painting colorful portraits of people in my dreams. Then one night I dreamt I had a great art show of my paintings. Truly I was really excited and asked my mom how I could truly make my dream come true. I was frankly told it could not very much happen unless I painted in real life. Truly I was surprised to see I could, by kindly trying hard, to learn to paint.",
      "I thought everyone could see great color everywhere: around people, other living creatures, in cities and in nature. Frankly I believed everyone had glorious dreams, until I told people about the paintings in my dreams; they were very surprised.",
      "I was born in Paris, France and I loved to follow the beautiful patterns in the ceramic and mosaic tile floors in old buildings and cathedrals. Museums were full of bright paintings I loved to look at out of the corner of my eye. Then came England before moving to San Diego at the age of 7. I grew up inspired by the beautiful ocean.",
      "Frankly my development as a child was not typical and the doctors gave me the diagnosis of severe autism. They told my parents to put me in an institution and to get on with their lives.",
    ],
    image: "Jermey.png",
    visual1: "jeremy1.PNG",
    visual2: "jeremy2.PNG",
    visual3: "jeremy3.PNG",
  },
  {
    name: "Ali Shahrouzi",
    bio: [
      "My name is Ali Shahrouzi. I am a visionary artist. I paint my dreams.",
      "I’ve been in love with photography since I was 14. First my brother helped me; when he got too busy, I started getting students to assist me,” said Ali Shahrouzi (left) while shooting photos with his current assistant Conor Daniels at Alice Keck Park Memorial Gardens. Shahrouzi is a disabled fine-art photographer who specializes in film and darkroom work. Daniels, who has been helping out for four months, said, “This is a win-win situation because we both learn from each other.",
    ],
    image: "alidaniels.jpg",
    visual1: "ali1.jpg",
    visual2: "ali2.jpg",
    visual3: "ali3.jpg",
  },
  {
    name: "Marrie Bottleson",
    bio: [
      "Hi, my name is Marrie Bottelson. I'm an artist. Because my art makes me happy and I want others to look at my art work and they  feel happy. I also mark art to stand up for myself, to feel proud and to show the world that it takes a lot of strength for me to make art.",
      "I like working with acrylic paints on canvas. I like how paint feels when I’m moving it around with a brush and I like to see what I can do with it. I used to paint fish and trees, but now I’m into cats and dogs.",
      "I hope you like my artwork",
    ],
    image: "marrie.png",
    visual1: "marrie1.jpg",
    visual2: "marrie2.jpg",
    visual3: "marrie3.JPG",
  },
  {
    name: "Matt Sully",
    bio: [
      "My name is Matthew 'Sully' Sullivan, and I am an artist.",
      "I was born with Cerebral Palsy, but that has not stopped me from going after my creative dreams. Through the encouragement of my high school teacher, Mr. Sporn, and my caretaker, Liz, I have found ways to express myself through art.",
      "Painting and sketching allow me to show others how my mind works. Although I do things a little differently than others and some have seen that as a disability, I find that what makes me different is a strength. My art is inspired by my story, and now I want to share my story with you.",
      "I hope you enjoy.",
    ],
    image: "matt.png",
    visual1: "matt1.jpg",
    visual2: "matt2.jpg",
    visual3: "matt3.jpg",
  },
  {
    name: "John Bramblitt",
    bio: [
      "My name is John Bramblitt",
      "I see the world differently now than when I was sighted, both in a physical way but also emotionally, these paintings are my most earnest and sincere means of trying to understand what true perception is. When I lost my sight I thought I would be cast into a world of darkness; to my surprise this is not what happened. Being an artist this gave me a way to explore this new perceptual world that I found myself in, and more importantly a way to reach out and connect with those around me.",
      "Color has more meaning for me since having lost my vision, and in truth the world is a far more colorful place now than when I was sighted. I am no longer limited to the arbitrary colors of objects, in other words the color that is seen when light reflects off of something. Color of this kind has more to do with the type and quality of light being reflected than of any essential quality about the object itself. Color is so much more than this – it is emotion and feeling; for me it is the expression of the inner unseen nature of the object or person being observed.",
      "The way that I ‘see’ with my hands is real and concrete – I visualize, in my mind, through touch. I also see color when I hear music – I always have – it’s called , but it’s an ability that has become stronger over the years since losing my sight. Because of these odd relationships, of using senses in unusual ways, I began to wonder how else the senses may harmonize with one another.",
      "Color is the perfect vehicle to express the senses, because there is an almost infinite range of colors to choose from, and they interact with each other in complex ways (blending, mixing, complementing, contrasting, etc.) which elegantly mirrors even the most complex sensory reactions. Color can easily express, for example, the high and low notes of a glass of wine, and how the flavors interrelate and mingle together to affect the palette. Or to portray the way the notes of a piece of music weave and interact with one another to create their emotional strength.",
      "Many of my pieces include figurative or written elements; I think of these as the bones of the painting; they are the framework on which the color of the painting hangs. The imagery provided serves to guide our focus to the ideas and emotions being carried by the abstract use of color in the painting. I enjoy using combinations of both figurative and abstract elements in my work; to me it most accurately represents the blending of the physical, intellectual, and emotional aspects that all come together to form our perception.",
      "The world around us is filled with poetry; with physical metaphors that add to our understanding and give breadth and depth to our lives. They add color and vitality to what otherwise could be a very bleak and unremarkable landscape. With the right kind of eyes you can see beneath the skin of things; you can lift the veil, and see to the true color of what lies around us.",
    ],
    image: "John.png",
    visual1: "john1.jpg",
    visual2: "john2.jpg",
    visual3: "john3.jpg",
  },
];
